
Welcome! This is the course website for MATH 168: Introduction to Networks at UCLA, as taught by Dr. Phil Chodrow, in Spring Quarter of 2022. 
Its primary purpose is to house lecture notes and other course resources.

In this course, we'll study some of the primary questions we can ask about networks from a mathematical point of view. These questions include: 

- What kind of things is it useful to **measure** in networks?
- What are some **properties** shared by many real-world networks?
- What **mathematical models** are useful for understanding some of these properties? 
- What kinds of algorithms can we use to extract insights from network data? 

Along the way, we'll build our mathematical toolboxes, especially those related to linear algebra and probability. 

## Figure Code {.unnumbered}

This site includes some figures, such as the one above, that I have generated with code. You can click the "Code" button right above the figure to view the code that created it. This code will often be in R, although I will make some effort to demonstrate some techniques with Python and NetworkX as well. 

